site_name: Acheron Docs
site_url: http://acheronproject.com
site_author: Gondolindrim
site_description: Acheron Project documentation
repo_url: https://github.com/AcheronProject/AcheronDocs
repo_name: AcheronProject/AcheronDocs

nav:
    - Home: index.md
    - About: overview.md
    - Articles:
        - About the articles: articles.md
        - A single-push reset circuit for STM32, part 1: reset_article_1/reset_article_1.md
        - A single-push reset circuit for STM32, part 2: reset_article_2/reset_article_2.md
        - A multi-MCU approach to keyboard PCB development: joker_mcus/joker.md
    - AOHL v1.4: AOHL14.md
    - Alexandria: alexandria/alexandria.md
    - PCB repository:
         - Introduction to the Acheron PCBs: pcbs/intro_to_pcbs.md
         - Apollo: pcbs/apollo/apollo.md
         - Freya: pcbs/freya/freya.md
         - Shark: pcbs/shark/shark.md
         - Raphael: pcbs/raphael/raphael.md
    - Electric Symbols: electric_symbols/electric_symbols.md
    - Acheron Setup: acheron_setup/acheron_setup.md

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tabbed
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
            custom_icons:
                - images/icons

theme:
  name: material
  palette:
    - scheme: acheron-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: acheron-dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: images/icons/acheron_favicon.svg
  logo: images/icons/acheron_favicon.svg
  features:
    - navigation.tabs

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/AcheronProject/AcheronDocs
          name: See the Acheron Docs GitHub

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - extra_css/pymdownx_tabbed.css
